import React from 'react';
import { ImageIcon, DownloadIcon, SparklesIcon } from './icons';

interface ImageDisplayProps {
  isLoading: boolean;
  error: string | null;
  generatedImage: string | null;
  aspectRatio: string;
  onRefine: () => void;
  refinementPrompt: string;
  setRefinementPrompt: (prompt: string) => void;
  isEnhancing: boolean;
  onEnhanceAndDownload: () => void;
}

const ImageDisplay: React.FC<ImageDisplayProps> = ({ 
  isLoading, error, generatedImage, aspectRatio,
  onRefine, refinementPrompt, setRefinementPrompt,
  isEnhancing, onEnhanceAndDownload
}) => {
  const getAspectRatioClass = (ratio: string) => {
    switch (ratio) {
      case "16:9": return "aspect-[16/9]";
      case "9:16": return "aspect-[9/16]";
      case "4:3": return "aspect-[4/3]";
      case "3:4": return "aspect-[3/4]";
      case "1:1":
      default:
        return "aspect-square";
    }
  };

  const showPlaceholderContent = !isLoading && !error && !generatedImage;

  return (
    <div className="space-y-4">
      <div className={`relative group w-full max-w-2xl mx-auto bg-base-300 dark:bg-dark-base-300 rounded-2xl shadow-inner overflow-hidden flex items-center justify-center transition-all duration-300 ${!generatedImage || isLoading ? getAspectRatioClass(aspectRatio) : ''}`}>
        {isLoading && (
          <div className="flex flex-col items-center justify-center text-base-content-secondary dark:text-dark-content-secondary animate-pulse-slow p-8 text-center">
            <ImageIcon className="w-16 h-16 mb-4" />
            <p className="font-semibold text-lg">Generating your masterpiece...</p>
            <p className="text-sm">This can take a moment. Please wait.</p>
          </div>
        )}
        {error && !isLoading && (
          <div className={`flex flex-col items-center justify-center text-red-600 p-8 text-center w-full h-full`}>
            <p className="font-bold">Operation Failed</p>
            <p className="text-sm mt-2">{error}</p>
          </div>
        )}
        {!isLoading && !error && generatedImage && (
          <img
            src={generatedImage}
            alt="Generated by AI"
            className="w-full h-auto object-contain animate-fade-in"
          />
        )}
        {showPlaceholderContent && (
          <div className="flex flex-col items-center justify-center text-base-content-secondary dark:text-dark-content-secondary p-8 text-center">
            <ImageIcon className="w-16 h-16 mb-4" />
            <h3 className="text-lg font-semibold text-base-content dark:text-dark-content">Your Image Awaits</h3>
            <p className="text-sm text-base-content-secondary dark:text-dark-content-secondary">Enter a prompt and click "Generate" to create an image.</p>
          </div>
        )}
      </div>

      {!isLoading && generatedImage && (
        <div className="w-full max-w-2xl mx-auto bg-base-100 dark:bg-dark-base-100 p-4 rounded-2xl shadow-lg animate-fade-in">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
            <a
              href={generatedImage}
              download="ai-generated-image-standard.jpg"
              className="w-full flex items-center justify-center bg-gray-200 dark:bg-gray-700 text-base-content dark:text-dark-content font-bold py-2 px-4 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
            >
              <DownloadIcon className="w-5 h-5 mr-2" />
              Download Standard
            </a>
            <button
              onClick={onEnhanceAndDownload}
              disabled={isEnhancing}
              className="w-full flex items-center justify-center bg-gradient-to-r from-brand-primary to-brand-secondary text-white font-bold py-2 px-4 rounded-lg hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed transition-opacity duration-200"
            >
              {isEnhancing ? (
                <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
              ) : (
                <SparklesIcon className="w-5 h-5 mr-2" />
              )}
              {isEnhancing ? 'Enhancing...' : 'Enhance & Download'}
            </button>
          </div>
          
          <div className="pt-4 border-t border-base-200 dark:border-dark-base-300">
            <h3 className="text-md font-semibold text-base-content dark:text-dark-content mb-3">Refine Image</h3>
            <div className="space-y-3">
              <textarea
                value={refinementPrompt}
                onChange={(e) => setRefinementPrompt(e.target.value)}
                placeholder="e.g., Change pose to look to the left, add a hat"
                className="w-full p-2 bg-base-200 dark:bg-dark-base-300 text-base-content dark:text-dark-content border border-base-300 dark:border-dark-base-300 rounded-lg focus:ring-2 focus:ring-brand-primary focus:border-brand-primary transition duration-200"
                rows={2}
              />
              <button
                onClick={onRefine}
                disabled={!refinementPrompt.trim()}
                className="w-full flex items-center justify-center bg-gray-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                <SparklesIcon className="w-5 h-5 mr-2" />
                Generate Refinement
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ImageDisplay;