import React from 'react';
import { ImageIcon, DownloadIcon } from './icons';

interface ImageDisplayProps {
  isLoading: boolean;
  error: string | null;
  generatedImage: string | null;
  aspectRatio: string;
}

const ImageDisplay: React.FC<ImageDisplayProps> = ({ isLoading, error, generatedImage, aspectRatio }) => {
  const getAspectRatioClass = (ratio: string) => {
    switch (ratio) {
      case "16:9": return "aspect-[16/9]";
      case "9:16": return "aspect-[9/16]";
      case "4:3": return "aspect-[4/3]";
      case "3:4": return "aspect-[3/4]";
      case "1:1":
      default:
        return "aspect-square";
    }
  };

  const showPlaceholderContent = !isLoading && !error && !generatedImage;

  return (
    <div className={`relative group w-full max-w-2xl mx-auto bg-base-300 rounded-2xl shadow-inner overflow-hidden flex items-center justify-center transition-all duration-300 ${!generatedImage || isLoading ? getAspectRatioClass(aspectRatio) : ''}`}>
      {isLoading && (
        <div className="flex flex-col items-center justify-center text-base-content-secondary animate-pulse-slow p-8 text-center">
          <ImageIcon className="w-16 h-16 mb-4" />
          <p className="font-semibold text-lg">Generating your masterpiece...</p>
          <p className="text-sm">This can take a moment. Please wait.</p>
        </div>
      )}
      {error && !isLoading && (
        <div className={`flex flex-col items-center justify-center text-red-600 p-8 text-center w-full h-full`}>
          <p className="font-bold">Generation Failed</p>
          <p className="text-sm mt-2">{error}</p>
        </div>
      )}
      {!isLoading && !error && generatedImage && (
        <>
          <img
            src={generatedImage}
            alt="Generated by AI"
            className="w-full h-auto object-contain animate-fade-in"
          />
          <a
            href={generatedImage}
            download="ai-generated-image.jpg"
            className="absolute bottom-4 right-4 bg-black bg-opacity-50 text-white p-2 rounded-full hover:bg-opacity-75 transition-opacity opacity-0 group-hover:opacity-100"
            aria-label="Download image"
          >
            <DownloadIcon className="w-6 h-6" />
          </a>
        </>
      )}
      {showPlaceholderContent && (
        <div className="flex flex-col items-center justify-center text-base-content-secondary p-8 text-center">
          <ImageIcon className="w-16 h-16 mb-4" />
          <h3 className="text-lg font-semibold">Your Image Awaits</h3>
          <p className="text-sm">Enter a prompt and click "Generate" to create an image.</p>
        </div>
      )}
    </div>
  );
};

export default ImageDisplay;